export const deck = [
  // Hearts
  { showFront: false, suitSymbol: '♥', suit: 'Hearts', value: 'A', suitColor: 'red' },
  { showFront: false, suitSymbol: '♥', suit: 'Hearts', value: '2', suitColor: 'red' },
  { showFront: false, suitSymbol: '♥', suit: 'Hearts', value: '3', suitColor: 'red' },
  { showFront: false, suitSymbol: '♥', suit: 'Hearts', value: '4', suitColor: 'red' },
  { showFront: false, suitSymbol: '♥', suit: 'Hearts', value: '5', suitColor: 'red' },
  { showFront: false, suitSymbol: '♥', suit: 'Hearts', value: '6', suitColor: 'red' },
  { showFront: false, suitSymbol: '♥', suit: 'Hearts', value: '7', suitColor: 'red' },
  { showFront: false, suitSymbol: '♥', suit: 'Hearts', value: '8', suitColor: 'red' },
  { showFront: false, suitSymbol: '♥', suit: 'Hearts', value: '9', suitColor: 'red' },
  { showFront: false, suitSymbol: '♥', suit: 'Hearts', value: '10', suitColor: 'red' },
  { showFront: false, suitSymbol: '♥', suit: 'Hearts', value: 'J', suitColor: 'red' },
  { showFront: false, suitSymbol: '♥', suit: 'Hearts', value: 'Q', suitColor: 'red' },
  { showFront: false, suitSymbol: '♥', suit: 'Hearts', value: 'K', suitColor: 'red' },

  // Diamonds
  { showFront: false, suitSymbol: '♦', suit: 'Diamonds', value: 'A', suitColor: 'red' },
  { showFront: false, suitSymbol: '♦', suit: 'Diamonds', value: '2', suitColor: 'red' },
  { showFront: false, suitSymbol: '♦', suit: 'Diamonds', value: '3', suitColor: 'red' },
  { showFront: false, suitSymbol: '♦', suit: 'Diamonds', value: '4', suitColor: 'red' },
  { showFront: false, suitSymbol: '♦', suit: 'Diamonds', value: '5', suitColor: 'red' },
  { showFront: false, suitSymbol: '♦', suit: 'Diamonds', value: '6', suitColor: 'red' },
  { showFront: false, suitSymbol: '♦', suit: 'Diamonds', value: '7', suitColor: 'red' },
  { showFront: false, suitSymbol: '♦', suit: 'Diamonds', value: '8', suitColor: 'red' },
  { showFront: false, suitSymbol: '♦', suit: 'Diamonds', value: '9', suitColor: 'red' },
  { showFront: false, suitSymbol: '♦', suit: 'Diamonds', value: '10', suitColor: 'red' },
  { showFront: false, suitSymbol: '♦', suit: 'Diamonds', value: 'J', suitColor: 'red' },
  { showFront: false, suitSymbol: '♦', suit: 'Diamonds', value: 'Q', suitColor: 'red' },
  { showFront: false, suitSymbol: '♦', suit: 'Diamonds', value: 'K', suitColor: 'red' },

  // Clubs
  { showFront: false, suitSymbol: '♣', suit: 'Clubs', value: 'A', suitColor: 'black' },
  { showFront: false, suitSymbol: '♣', suit: 'Clubs', value: '2', suitColor: 'black' },
  { showFront: false, suitSymbol: '♣', suit: 'Clubs', value: '3', suitColor: 'black' },
  { showFront: false, suitSymbol: '♣', suit: 'Clubs', value: '4', suitColor: 'black' },
  { showFront: false, suitSymbol: '♣', suit: 'Clubs', value: '5', suitColor: 'black' },
  { showFront: false, suitSymbol: '♣', suit: 'Clubs', value: '6', suitColor: 'black' },
  { showFront: false, suitSymbol: '♣', suit: 'Clubs', value: '7', suitColor: 'black' },
  { showFront: false, suitSymbol: '♣', suit: 'Clubs', value: '8', suitColor: 'black' },
  { showFront: false, suitSymbol: '♣', suit: 'Clubs', value: '9', suitColor: 'black' },
  { showFront: false, suitSymbol: '♣', suit: 'Clubs', value: '10', suitColor: 'black' },
  { showFront: false, suitSymbol: '♣', suit: 'Clubs', value: 'J', suitColor: 'black' },
  { showFront: false, suitSymbol: '♣', suit: 'Clubs', value: 'Q', suitColor: 'black' },
  { showFront: false, suitSymbol: '♣', suit: 'Clubs', value: 'K', suitColor: 'black' },

  // Spades
  { showFront: false, suitSymbol: '♠', suit: 'Spades', value: 'A', suitColor: 'black' },
  { showFront: false, suitSymbol: '♠', suit: 'Spades', value: '2', suitColor: 'black' },
  { showFront: false, suitSymbol: '♠', suit: 'Spades', value: '3', suitColor: 'black' },
  { showFront: false, suitSymbol: '♠', suit: 'Spades', value: '4', suitColor: 'black' },
  { showFront: false, suitSymbol: '♠', suit: 'Spades', value: '5', suitColor: 'black' },
  { showFront: false, suitSymbol: '♠', suit: 'Spades', value: '6', suitColor: 'black' },
  { showFront: false, suitSymbol: '♠', suit: 'Spades', value: '7', suitColor: 'black' },
  { showFront: false, suitSymbol: '♠', suit: 'Spades', value: '8', suitColor: 'black' },
  { showFront: false, suitSymbol: '♠', suit: 'Spades', value: '9', suitColor: 'black' },
  { showFront: false, suitSymbol: '♠', suit: 'Spades', value: '10', suitColor: 'black' },
  { showFront: false, suitSymbol: '♠', suit: 'Spades', value: 'J', suitColor: 'black' },
  { showFront: false, suitSymbol: '♠', suit: 'Spades', value: 'Q', suitColor: 'black' },
  { showFront: false, suitSymbol: '♠', suit: 'Spades', value: 'K', suitColor: 'black' }
]
