name: learning-actions

on:
  pull_request:
    branches:    
      - master
      - adding-pipeline
  push:
    branches:    
      - adding-pipeline
jobs:
  lint:
    name: Lint Code.
    runs-on: macos-13
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - run: echo "Unleash the Lint Roller!"
      # - run: npm ci
      # - run: npm run build --if-present
      # - run: npm test
    
      
  test:
    runs-on: macos-13
    name: Test Code.
    needs: lint
    steps:
      - run: echo "Hello World"
  build:
    runs-on: macos-13
    name: Build Code.
    needs: [lint, test]
    steps:
      - run: echo "Hello World"
  deploy:
    runs-on: macos-13
    name: Deploy changes
    needs: [lint, test, build]
    steps:
      - run: echo "Hello World"

